# Generated by Django 5.2 on 2025-04-19 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_api', '0002_game_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='column',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='move',
            name='row',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='move',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AddConstraint(
            model_name='move',
            constraint=models.CheckConstraint(condition=models.Q(('row__gte', 0), ('row__lte', 8)), name='row_within_bounds'),
        ),
        migrations.AddConstraint(
            model_name='move',
            constraint=models.CheckConstraint(condition=models.Q(('column__gte', 0), ('column__lte', 8)), name='column_within_bounds'),
        ),
        migrations.AddConstraint(
            model_name='move',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0), ('value__lte', 9)), name='value_within_bounds'),
        ),
    ]
